version: "2"

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  build-tags:
    - integration
    - unit

  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace

  settings:
    govet:
      disable-all: true
      enable:
        - assign
        - bools
        - framepointer
        - shadow
        - stringintconv
        - structtag

    gocyclo:
      # minimal code complexity to report, 30 by default
      min-complexity: 26

    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/davecgh/go-spew/spew"

    misspell:
      ignore-rules:
        - newrelic

    lll:
      line-length: 150

    nolintlint:
      allow-unused: false
      require-specific: true

issues:
  # disable limits on issue reporting
  max-per-linter: 0
  max-same-issues: 0
