version: "2"

# options for analysis running
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

  build-tags:
    - integration
    - unit

  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - gocyclo
    - govet
    - misspell
    - nolintlint
    - whitespace

  settings:
    govet:
      disable-all: true
      enable:
        - assign
        - bools
        - shadow
        - stringintconv
        - structtag

    gocyclo:
      min-complexity: 26

    misspell:
      ignore-rules:
        - newrelic

    nolintlint:
      allow-unused: false
      require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
