project_name: tutone

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: tutone
    dir: cmd/tutone
    binary: tutone
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.appName={{.Binary}}

release:
  name_template: "{{.ProjectName}} v{{.Version}}"

archives:
  - id: "default"
    builds:
      - newrelic
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md

dockers:
  - dockerfile: build/package/Dockerfile
    image_templates:
      - "newrelic/tutone:{{ .Tag }}"
      - "newrelic/tutone:v{{ .Major }}.{{ .Minor }}"
      - "newrelic/tutone:latest"
    binaries:
      - tutone
    build_flag_templates:
      - "--pull"
      - "--label=repository=http://github.com/newrelic/tutone"
      - "--label=homepage=https://developer.newrelic.com/"
      - "--label=maintainer=Developer Toolkit <opensource@newrelic.com>"

# Already using git-chglog
changelog:
  skip: true

